"""empty message

Revision ID: 9420852e987c
Revises: f90ce3b8a545
Create Date: 2023-02-03 20:02:24.685181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9420852e987c'
down_revision = 'f90ce3b8a545'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
